### PR TITLE
Upgrade: bs-platform@4, reason-react@0.5

### PR DESCRIPTION
**Pull request by thangngoc89**
This is a breaking change that upgrade important dependencies.

### CODE REVIEW

**Comment by thangngoc89** [comment]
Hello, since you edited the README saying that this package is deprecated, could you please explain the reason behind it? (like lack of times, not recommended methods, ...) I would happy to take over maintenance  of this repository since I'm maintaining a fork already

**Comment by arialpew** [comment]
Hello @thangngoc89,

Sorry for the late response, i haven't worked on this repository for several months. Originally, it was an experiment.

I've never found a perfect way to work with code-splitting and BuckleScript / ReasonML. I've tried several possible API, but none allow :

- Guarantee the safety of module type implicitly.
- No additional file than the ".re" file to import.
- No magic (bs.raw / obj.magic or weird/unsafe tricks).

Today, there is still no consensual solution for working with dynamic import with BuckleScript (I haven't found any information that goes in that direction).

React now offers the Lazy and Suspense API so I guess sooner or later this problem will be solved definitively by the ReasonReact side project.

**Comment by thangngoc89** [comment]
I think suspend should be the way to do this. There is an issue on bucklescript's repository requesting dynamic imports support. For now, I think that this repo is the best way can get.

**Comment by arialpew** [comment]
I added you as contributors on NPM and the GitHub repo, you should be able to merge stuff, remove deprecated warning in README and release new version if you feel it necessary 👍 .

If something goes wrong, leave me a quick message on ReasonML Discord or at Twitter (@RobinMeillet).

**Comment by gabrielperales** [comment]
@kMeillet @thangngoc89 any change in this PR? I've been working on updating it to 0.7.0, but I'm having an issue with Hooks inside the HOC...

**Comment by arialpew** [comment]
It's been a long time.

Dynamic import still does not seem to be supported by BuckleScript (unless I miss some information somewhere ^^) . I merged the changes from @thangngoc89  to support bs-platform@4 and reason-react@0.5.

Original BuckleScript issue :

https://github.com/BuckleScript/bucklescript/issues/2765

Homewever, React Suspense is available in ReasonReact now. Good news ! There's a demo in this repository : https://github.com/jchavarri/reason-react-lazy-loading

I will work on that soon.

@gabrielperales  Did you manage to run reason-loadable with reason-react@0.7 ?

**Comment by gabrielperales** [comment]
@kMeillet nope. I had a deadline and at the end I decided to not do coding splitting, but I'll give it a try again soon :). BTW, thank you for sharing the @jchavarri repo, I'll check it out.

**Comment by arialpew** [comment]
I made a new release (v0.5.0) with updated dependencies. Now, we are up to date :) .

This version support latest bs-platform (v5) and reason-react (v0.7).

I will work on a new release tomorrow with React.Suspense/Lazy demo and JSX v3 support.

**Edit :** "reason-loadable" v0.6.1 support Hook, React.Suspense/Lazy. We handle JSX v2 (record component) and JSX v3 (hook component).  👍

**Pull request merged**
